# Generated by Django 6.0.5 on 2026-06-03 13:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="fetched_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AddField(
            model_name="price",
            name="source",
            field=models.CharField(default="yfinance", max_length=20),
        ),
        migrations.AddIndex(
            model_name="price",
            index=models.Index(
                fields=["asset", "date"], name="prices_asset_i_0b63a7_idx"
            ),
        ),
    ]
