# Generated by Django 6.0.5 on 2026-06-06 00:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_price_source_fetchedat_index'),
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forecastjob',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='forecastjob',
            name='celery_task_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='forecastjob',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='forecastjob',
            index=models.Index(fields=['status', 'created_at'], name='forecast_fo_status_12570d_idx'),
        ),
    ]
