# Generated by Django 6.0.5 on 2026-06-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_migrate_strategies_list_to_dict"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfoliojob",
            name="data_source",
            field=models.CharField(
                choices=[
                    ("coingecko", "CoinGecko"),
                    ("fallback", "Fallback"),
                    ("cache", "Cache"),
                ],
                default="coingecko",
                max_length=20,
            ),
        ),
    ]
